# Generated by Django 3.2.9 on 2021-11-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='banner',
            field=models.ImageField(upload_to='movie/images'),
        ),
    ]
