# Generated by Django 3.2.9 on 2021-11-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='production_date',
            field=models.DateField(null=True),
        ),
    ]
