# Generated by Django 3.2.9 on 2021-11-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner',
            field=models.ImageField(default=' ', upload_to='movie/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(default=2, upload_to='movie/videos'),
            preserve_default=False,
        ),
    ]
