# Generated by Django 3.2.9 on 2021-11-07 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_alter_review_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idnumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='id_name',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='movie.idnumber'),
            preserve_default=False,
        ),
    ]
