# Generated by Django 3.2.9 on 2021-11-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_auto_20211107_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idnumber',
            name='number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
